### ISSUE TITLE
GP_EVENT_FILE_CHANGED is not found in libgphoto2 (Developed on the 2.5.21 release)

### ISSUE THREAD

**Issue by LauraYan** [BYU-AUVSI/a6000_ros#18]
There is a compiling error for this variable - GP_EVENT_FILE_CHANGED in the a6000_ros-master/src/driver/trigger_capture.c. 
in the the 2.5.21 release of libgphoto2 library, the file gphot2-camera.h will show up this item

typedef enum {
	GP_EVENT_UNKNOWN,	/**< unknown and unhandled event. argument is a char* or NULL */
	GP_EVENT_TIMEOUT,	/**< timeout, no arguments */
	GP_EVENT_FILE_ADDED,	/**< CameraFilePath* = file path on camfs */
	GP_EVENT_FOLDER_ADDED,	/**< CameraFilePath* = folder on camfs */
	GP_EVENT_CAPTURE_COMPLETE	/**< last capture is complete */
} CameraEventType;

Could you update your used version of libgphoto2? 
Or could you show me how to solve it?

**Comment by len0rd** [comment]
Unfortunately I do not currently have access to a working a6000 to test any driver/lib changes against. But I'm happy to look over any PRs that update gphoto or the drivers! Just know any updates to have the code work with a newer libgphoto should also update the corresponding docs.

If the only libgphoto2 installation on your machine was installed via the `./install_deps.sh` script in the repo root, things should compile and work. If you can verify that the only libgphoto2 installation on your machine was installed via that script and things still dont compile, I can look into it a little more

**Comment by LauraYan** [comment]
Hi There,
 Thank you for you email.
  I deleted the old gphoto library in the /user directory. Now I got error
of not finding GPHOTO library.
Could you teach me how to make the install-deeps.sh to work?
Thank you.

**Comment by LauraYan** [comment]
Hi len0rd,
 I think I missed step or tool to make the .install_deps.sh work. Could you
teach me how to use it?
Thank you very much.

**Comment by LauraYan** [comment]
Solved the issue after running ./install_deps.sh. Thank you for your help. Sorry, this issue isn't a true issue, please close it.
